insert links images and button
kely-rufino/portfolio pull request #3
Opened 2021-11-23 21:54 UTC by kely-rufino

It's almost complete. 
What do you think about it? Any suggestions how to make this better? 
Thank for any suggestions.

2021-11-24 10:21 UTC, luciavelasco commented on index.html
> +<html lang="en" xmlns="http://www.w3.org/1999/html">
Probably remove this change; this value is set by default in HTML5 and is invalid in HTML4.

2021-11-24 10:23 UTC, luciavelasco commented on index.html
> +<a id="top"></a>
Put this ID on the topmost element (i.e. the flower-wrapper div on line 13), as you shouldn't need a separate element for this. If it doesn't work, make it a span tag or a div (as an anchor tag should ALWAYS be a link, whereas spans and divs can be anything or nothing)

2021-11-24 10:26 UTC, luciavelasco requested changes
Two things:
- please don't merge this until you have an approval
- make a new branch every time instead of making a pull request on the same branch!
A branch should only contain the work that goes into one pull request for one feature.

About the code:
I'm still looking through it, but I love how you made the flower petals! Use top/right/bottom/left instead of margin.

2021-11-24 10:28 UTC, luciavelasco commented on index.html
> +                <a href="https://github.com/kely-rufino" target="_blank"> Github </a>
put the anchor tag around the div, instead of around the text, that way you can click anywhere on the petal

2021-11-24 10:28 UTC, luciavelasco commented on index.html
> +                <a href="#about">About</a>
move the anchor tag, same as above

2021-11-24 10:28 UTC, luciavelasco commented on index.html
> +            <div class="petal-linkedin-link"><a href="https://www.linkedin.com/in/kely-rufino" target="_blank">
same as above

2021-11-24 10:30 UTC, luciavelasco commented on index.html
> +                <a href="#contact">Contact Me</a></div>
same as above

2021-11-24 10:41 UTC, luciavelasco commented on index.html
> +            <div class="petal-gh-link">
You don't need this div! You can center the text for all of the links, instead of having a class for each of them, using:
- text-align
- padding-top
- font-size

And setting `box-model: border-box;` on all your elements. Try it and let me know if it makes sense.
The only thing you might need a class for is width; you can set that on the anchor tag itself instead of a div.

2021-11-24 10:42 UTC, luciavelasco commented on index.html
> +                <br> I got jobs in the hospitality industry, as well, but it is hardly someone can make a career of!
> but it is hardly someone

change to

> but it is hardly something someone

2021-11-24 10:43 UTC, luciavelasco commented on index.html
> +        <a href="#top">
This is really great, I really like this use of a fixed element!

2021-11-24 10:44 UTC, luciavelasco commented on portfolio.css
> +footer a img{
This is really excellent CSS!
I recommend giving it a class instead of using the elements, and probably applying the class to the anchor tag instead of the image. Nice use of text-decoration:none!

2021-11-24 10:45 UTC, luciavelasco requested changes
Excellent work! Some more changes to do, but it's very impressive.

2021-11-24 10:49 UTC, kely-rufino commented on index.html
> +<html lang="en" xmlns="http://www.w3.org/1999/html">
Thank you! :D

2021-11-24 13:51 UTC, kely-rufino commented on index.html
> +                <a href="https://github.com/kely-rufino" target="_blank"> Github </a>
I tried, but didn't work, the anchor tag don't go to the link.

2021-11-24 13:51 UTC, kely-rufino commented on index.html
> +                <a href="#about">About</a>
I tried, but didn't work, the anchor tag don't go to the link.

2021-11-24 13:51 UTC, kely-rufino commented on index.html
> +            <div class="petal-linkedin-link"><a href="https://www.linkedin.com/in/kely-rufino" target="_blank">
I tried, but didn't work, the anchor tag don't go to the link.

2021-11-25 12:42 UTC, kely-rufino commented on index.html
> +                <a href="https://github.com/kely-rufino" target="_blank"> Github </a>
done!

2021-11-25 12:42 UTC, kely-rufino commented on index.html
> +                <a href="#about">About</a>
done!

2021-11-25 12:42 UTC, kely-rufino commented on index.html
> +            <div class="petal-linkedin-link"><a href="https://www.linkedin.com/in/kely-rufino" target="_blank">
done!

2021-11-25 12:42 UTC, kely-rufino commented on index.html
> +                <a href="#contact">Contact Me</a></div>
done!

2021-11-25 12:42 UTC, kely-rufino commented on index.html
> +            <div class="petal-gh-link">
done

2021-11-25 12:52 UTC, merged